"""increased correct_answere size

Revision ID: 44ec05602eba
Revises: 35891a58c615
Create Date: 2021-08-12 20:55:52.332596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44ec05602eba'
down_revision = '35891a58c615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=1280),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('correct_answer',
               existing_type=sa.String(length=1280),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###
