"""Changed Questions column names and added 'section' column

Revision ID: bf0e2116e0a2
Revises: 232d65e9e1b2
Create Date: 2021-05-09 18:54:18.871652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf0e2116e0a2'
down_revision = '232d65e9e1b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('section', sa.String(length=128), nullable=True))
        batch_op.drop_column('correct')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct', sa.INTEGER(), nullable=True))
        batch_op.drop_column('section')
        batch_op.drop_column('correct_answer')

    # ### end Alembic commands ###
